invoice/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

app_name = 'invoice'

urlpatterns = [
	path('', views.index, name='index'),
]

invoiceplus/urls.py
from django.contrib import admin
from django.urls import path, include
# Uploaded Media Files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('all_safe_xxx_safe_all/', admin.site.urls),
	path('invoice/', include('invoice.urls', namespace='invoice')),
	path('dashboard/', include('service.urls', namespace='service')),
	path('', include('user.urls', namespace='user')),

]


# Media files URL 
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.contrib import admin

from django.conf.urls import (
    handler404, 
    handler500
)

from django.urls import path, include
from . import views

handler404 = 'service.views.custom_404'
handler500 = 'service.views.custom_500'


app_name = 'service'
urlpatterns = [
	path('', views.index, name='index'),
	path('home/', views.home, name='home'),
	# Manager
	path('invoices/', views.invoice, name='invoice'),
	path('invoices/<int:id>/', views.invoice_detail, name='invoice_detail'),
	path('add-invoice/', views.add_invoice, name='add_invoice'),	
	path('select/<int:id>/', views.select_item, name='select_item'),
	path('unselect/<int:id>/', views.unselect_item, name='unselect_item'),
	path('delete-invoice/<int:id>/', views.delete_invoice, name='delete_invoice'),	
	path('add/<int:service_id>/', views.cart_add, name='cart_add'),
	path('search/results/', views.search, name='search'),
	path('remove/<int:service_id>/', views.cart_remove, name='cart_remove'),
	path('created/', views.created, name='created'),
	path('customer-list/', views.customer_list, name='customer_list'),
	path('manager/profile/', views.manager_profile, name='manager_profile'),
	path('services/', views.service_list, name='service_list'),	
	path('<slug:category_slug>/', views.service_list, name='service_list_by_category'),
	path('<int:id>/<slug:slug>/', views.service_detail, name='service_detail'),
	
]

user/urls.py
from django.contrib import admin

from django.conf.urls import (
    handler404, 
    handler500
)

from django.urls import path, include
from . import views

handler404 = 'user.views.custom_404'
handler500 = 'user.views.custom_500'


app_name = 'user'
urlpatterns = [
	path('', views.index, name='index'),	
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('list-of-invoices/', views.list_invoices, name='list_invoices'),
	path('detail-invoice/', views.detail_invoice, name='detail_invoice'),
	path('profile/', views.customer_profile, name='customer_profile'),
]

invoice/models.py
from django.conf import settings
from django.db.models import Max
from django.db import models
from service.models import Service


User = settings.AUTH_USER_MODEL


class Invoice(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_invoices')
	select = models.BooleanField(default=False, null=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	is_paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return '{}'.format(self.id)

	# def get_date(self):
	# 	return self.modified.date()

	def get_absolute_url(self):
		return reverse('product:service_detail', kwargs=[self.id, self.slug])


	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())

class InvoiceItem(models.Model):
	invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='items')
	product = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='invoice_items')
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	# def __str__(self):
	# 	return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

service/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(unique=True, max_length=200, db_index=True)
	image = models.ImageField(upload_to='category_pics', blank=True)
		
	class Meta:
		ordering = ('name',)
		verbose_name = ('category')
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('service:service_list_by_category', args=[self.slug])

class Service(models.Model):
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='services')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(unique=True, max_length=200, db_index=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('service:service_detail', args=[self.id, self.slug])

invoice/forms.py
from django.contrib.auth import get_user_model
from django.forms import ModelChoiceField
from django import forms
from .models import Invoice

User = get_user_model()


class CartAddServiceForm(forms.Form):
	"""Add service to the cart between quantity 1-20."""
	SERVICE_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)] 

	# allow user to select quantity between 1-20
	quantity = forms.TypedChoiceField(choices=SERVICE_QUANTITY_CHOICES, coerce=int)
	# This indicate whether the quantity has to be added to the cart (False)
	# quantity has to be updated with the quantity (True)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)



class SendInvoiceToDropDownForm(forms.ModelForm):
	"""Save Username to send invoice to."""
	# Choice DropDown to select
	# customer to send to
	user = forms.ModelChoiceField(queryset=User.objects.order_by('id').filter(is_customer='True'))

	class Meta:
		model = Invoice
		fields = ('user',)
		labels = {'user': 'Username'}

invoice/views.py
from django.shortcuts import (
		render,
		redirect,
)

from .models import InvoiceItem


def index(request):
	return render(request, 'product/index.html')	

service/views.py
from django.shortcuts import (
		render, 
		redirect, 
		get_object_or_404
)

from django.contrib.auth.decorators import login_required

from django.http import Http404

import datetime

from django.contrib.auth import get_user_model


from invoice.models import Invoice, InvoiceItem

from invoice.forms import (
	CartAddServiceForm,
	SendInvoiceToDropDownForm

)


from django.views.decorators.http import require_POST

from .models import Service

from invoice.cart import Cart


from .models import (
	Category,
	Service,
)


from django.core.paginator import (
	Paginator, 
	EmptyPage,
	PageNotAnInteger
)


from django.db.models import Q


User = get_user_model()



def index(request):
	pass
	return render(request, 'service/index.html')


def home(request):
	pass
	return render(request, 'service/dashboard/home.html')

@login_required
def search(request):
	"""Search result."""
	query = request.GET.get('q')

	results = Invoice.objects.filter(Q(id__icontains=query)).distinct()

	context = {'results': results}

	return render(request, 'service/dashboard/manager/search.html', context)


@login_required
def invoice(request):
	"""List of invoices."""
	invoice_list = Invoice.objects.all()

	# Paginator
	paginator = Paginator(invoice_list, 5)

	page = request.GET.get('page')

	try:
		# create Page object for the given page
		invoice_list = paginator.page(page)

	except PageNotAnInteger:
		# If page is not an integer deliver first page
		invoice_list = paginator.page(1)
		
	except EmptyPage:
		# If page is out of range deliver last page of results
		invoice_list = paginator.page(paginator.num_pages)

	context = {
		'invoice_list':invoice_list,
		'page': page,
	}

	return render(request, 'service/dashboard/manager/invoices.html', context)	

@login_required
def add_invoice(request):
	"""
	create invoice and also display cart and items.
	"""
	if request.method == 'POST':
		cart = Cart(request)
		form = SendInvoiceToDropDownForm(request.POST or None)
		if form.is_valid():
			invoice = form.save()

			# persist item in cart
			for item in cart:
				InvoiceItem.objects.create(invoice=invoice,
											product=item['service'],
											price=item['price'],
											quantity=item['quantity']) 
			# clear the cart
			cart.clear()

			context = {'invoice':invoice}
			return render(request, 'service/dashboard/manager/created.html', context)

	else:
		form = SendInvoiceToDropDownForm()

	# Invoice Sender
	invoice_from = request.user

	# Today date
	today_date = datetime.datetime.today()

	cart = Cart(request)

	# Change service quantity before
	# placing an order
	for item in cart:
		# itinialize the form with the current quantity
		# and set the update field to True so that when
		# we submit the form to the cart_add view,
		# the current quantity is replaced with the new one.
		item['update_quantity_form'] = CartAddServiceForm(initial={'quantity': item['quantity'], 'update':True})


	context = {
			'form':form,
			'invoice_from': invoice_from,
			'cart': cart, 
			'today_date': today_date
	}
	

	return render(request, 'service/dashboard/manager/add_invoice.html', context)

@login_required
def invoice_detail(request, id):
	"""Include Foreign Key reverse look up."""
	invoice = get_object_or_404(Invoice, id=id)

	context = {'invoice':invoice}
	return render(request, 'service/dashboard/manager/invoice_detail.html', context)


@login_required
def select_item(request, id):
	"""Select invoice id on Invoice page."""
	invoice = get_object_or_404(Invoice, id=id)
	invoice.select = True
	invoice.save()

	return redirect('service:invoice')

@login_required
def unselect_item(request, id):
	"""Unselect invoice id on Invoice page."""
	invoice = get_object_or_404(Invoice, id=id)
	invoice.select = False
	invoice.save()

	return redirect('service:invoice')

@login_required
def delete_invoice(request, id):
	"""Delete invoice on Invoice page."""
	Invoice.objects.filter(select__exact=True).delete()

	return redirect('service:invoice')


@require_POST
def cart_add(request, service_id):
	"""
	Add service to cart or
	update quantities for existing services.
	"""
	cart = Cart(request)
	service = get_object_or_404(Service, id=service_id)
	form = CartAddServiceForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(service=service, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('service:add_invoice')

def cart_remove(request, service_id):
	"""Remove item from cart."""
	cart = Cart(request)
	service = get_object_or_404(Service, id=service_id)
	cart.remove(service)
	return redirect('service:add_invoice')

@login_required
def created(request):
	pass
	return render(request, 'service/dashboard/manager/created.html', context)

@login_required
def manager_profile(request):
	profile = User.objects.filter(manager=request.user.id)

	context = {'profile': profile }
	return render(request, 'service/dashboard/manager/manager_profile.html', context)

@login_required
def customer_list(request):
	customers = User.objects.filter(is_customer='True')

	context = {'customers':customers}
	return render(request, 'service/dashboard/manager/customer_list.html', context)


@login_required
def service_list(request, category_slug=None):
	"""
	List all the services.
	"""
	# Optional category_slug parameter 
	# used to filter by a given category
	category = None
	categories = Category.objects.all()
	services = Service.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		services = services.filter(category=category)

	context = {
			'category':category,
			'categories': categories,
			'services':services,
	}
	return render(request, 'service/service_pages/list.html', context)

@login_required
def service_detail(request, id, slug):
	"""Detail of each service."""
	# Expect id and slug parameter to retrieve the
	# service instance.
	service = get_object_or_404(Service, id=id, slug=slug, available=True)

	# This will help add the cart button
	# to the service detail page.
	cart_service_form = CartAddServiceForm(request.POST)

	context = {
		'service':service,
		'cart_service_form':cart_service_form
	}

	return render(request, 'service/service_pages/detail.html', context)


def custom_404(request):
	"""Handle error 404."""
	return render(request, 'templates/404.html')

def custom_500(request):
	"""Handle error 500."""
	return render(request, 'templates/500.html')

service/templates/service/dashboard/manager/add_invoice.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}

User

{% endblock %}



{% block content %}

<div class="container mt-5 mb-5">
	<div class="row">
		<div class="card" style="width: 80rem;">
		  <div class="card-body">
		  	 <div class="col-sm-12">
		  	 <b><h1>Invoice</h1></b>
		  	 	<p><b>{{ invoice_id }}</b></p>
			  	 <hr>
			 <p>From : <b>{{ invoice_from.get_full_name }}</p>
			  {{ invoice_from.manager.company_name }}
			 </b>
			 <p>Date : <b>{{ today_date|date:"D M d Y"}}</b></p></br>
		     <hr>
		     <div class="items mt-3">	
		     	<h3 class="header ml-5 mt-5">Your service cart</h3>
					<table class="cart mt-5 ml-5">
						<thead>
							<tr>
								<th>Service</th>
								<th>Description</th>
								<th></th>
								<th></th>
								<th>Unit price</th>
								<th>Unit total price</th>
							</tr>
						</thead>
						<tbody>
							{% for item in cart %}
								{% with service=item.service %}
									<tr>
										<td>{{ service.name }}</td>
										<td>{{ service.description }}</td>
										<td>
											<form action="{% url 'service:cart_add' service.id %}" method="post">
												{% csrf_token %}
												{{ item.update_quantity_form.quantity }}
												{{ item.update_quantity_form.update }}
												<button class="btn btn-info" type="submit" value="Update">Update</button>	
											</form>
										</td>
										<td><a class="btn btn-danger" href="{% url 'service:cart_remove' service.id %}">Remove</a></td>
										</td>
										<td class="num">${{ item.price }}</td>
										<td class="num">${{ item.total_price }}</td>
									</tr>
								{% endwith %}
							{% endfor %}
							<tr class="total">
								<td><b>Total</b></td>
								<td colspan="3"></td>
								<td class="num"></td>
								<td class="num"><b>${{ cart.get_total_price }}</b></td>
							</tr>
						</tbody>
					</table>
					<div class="container">
						<p class="text-right mt-3 mr-5">
							<a href="{% url 'service:service_list' %}" class="button light">Add Service</a>
							</br>
							</br>
							<div class="col-sm-3 ml-3">
								<form action="." method="post" class="order-form">
								 	{% csrf_token %}
								 	{{ form|crispy }}
								 	</br>
							 		<button class="btn btn-primary" type="submit" value="Place order">Save & Close</button>
								</form>	
							</div>
						</p>
					</div>
				</h1>
		     </div>
		  </div>
		</div>
	</tr>
</div>

{% endblock %}

service/templates/service/dashboard/manager/created.html
{% extends "base.html" %}
{% load static %}


{% block title %}

Invoice-creation-successful

{% endblock %}



{% block content %}

<div class="container mt-5 ml-5">
	<div class="row">
		<h4>Invoice created. Thank you.</h4>
	</div>
	</br>
	<a href="{% url 'service:invoice' %}" class="button light">Go back to list of products.</a>
</div>

{% endblock %}

service/templates/service/dashboard/manager/customer_list.html
{% extends "base.html" %}
{% load static %}


{% block title %}

Customers list

{% endblock %}



{% block content %}

<div class="container mt-5">
	<div class="row">
		<div class="header">
			<h2>List of customers</h2></br>
			{% for customer in customers %}
				<p>{{ customer }}</p></br>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

service/templates/service/dashboard/manager/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}



{% endblock %}



{% block content %}

<div class="container mt-5">
	<div class="row">
		<p>Home</p>
	</div>
</div>

{% endblock %}

service/templates/service/dashboard/manager/invoice_detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}

Invoice detail

{% endblock %}



{% block content %}

<div class="container mt-5 mb-5">
	<div class="row">
		<div class="card" style="width: 80rem;">
		  <div class="card-body">
		  	 <div class="col-sm-12">
		  	 <b><h1>Invoice # {{ invoice.id }} </h1></b>
		  	 	<p><b>{{ invoice_id }}</b></p>
			  	 <hr>
			 <p>From : <b>{{ invoice.user }}</p>
			  {{ invoice_from.manager.company_name }}
			 </b>
			 <p>Date : <b>{{ invoice.created|date:"D M d Y"}}</b></p></br>
		     <hr>
		     <div class="items mt-3">	
		     	<h3 class="header ml-5 mt-5">Invoice items</h3>
					<table class="cart mt-5 ml-5">
						<thead>
							<tr>
								<th>Service</th>
								<th>Description</th>
								<th></th>
								<th></th>
								<th>Unit price</th>
								<th>Unit total price</th>
							</tr>
						</thead>
						<tbody>

							<!-- Foreign Key Reverse look up -->

							{% for invoice_item in invoice.items.all %}
								<tr>
									<td>{{ invoice_item.product.name }}</td>
									<td>{{ invoice_item.product.description }}</br></td>
									<td class="num"></td>
									<td class="num"></td>
									<td class="num">${{ invoice_item.product.price }}</td>
									<td class="num"></td>
								</tr>
							{% endfor %}
								<tr class="total">
									<td><b>Total</b></td>
									<td colspan="3"></td>
									<td class="num"></td>
									<td class="num"><b>${{ invoice.get_total_cost }}</b></td>
								</tr>		
						</tbody>
					</table>
				</h3>
				</br>
				<a href="{% url 'service:invoice' %}" class="button light ml-5">List of invoices</a>
				</br></br>
		     </div>
		  </div>
		</div>
	</tr>
</div>

{% endblock %}

service/templates/service/dashboard/manager/invoices.html
{% extends "base.html" %}
{% load static %}


{% block title %}

Invoices

{% endblock %}



{% block content %}

	<div class="container mt-5">

		<a href="{% url 'service:add_invoice' %}">
			<button type="button" class="btn btn-primary ml-auto mt-1 mb-4 ml-5">Create New Invoice</button>
	  	</a>

	  	<div class="search-bar mt-4">
        	<form method="GET" action="{% url 'service:search' %}">
          		{% csrf_token %}
          		<input type='text' name="q" value="{{ request.GET.q }}" placeholder="Search.."></input>
          		<input class='btn btn-info' type='submit' value='Search'/>
        	</form>
      	</div>
      	</br>
     	</br>

		<table>
		  <tr>
		    <th>Date</th>
		    <th>Invoice #</th>
		    <th>Client</th>
		    <th>Status</th>
		    <th>Total</th>
		    <th>Select Item</th>
		    <th>Send Email</th>
		    <th>Delete</th>
		  </tr>
		  {% for invoice in invoice_list %}
		  	{% if invoice.select == False %}
			  <tr>
			    <td>{{ invoice.created|date:"D M d Y" }}</td>
			    <td><a href="{% url 'service:invoice_detail' invoice.id %}" class="button light">{{ invoice.id }}</td>
			    <td>{{ invoice.user.username }}</td>
			    <td>sent: <b>{{ invoice.is_paid }}</b></td>
			    <td><b>{{ invoice.get_total_cost }}</b></td>
			    <td><a href="{% url 'service:select_item' invoice.id %}"><button class="btn btn-info" type="submit" value="Place order">Select</button></b></a></td>
			    <td><a href="#"><button class="btn btn-warning" type="submit" value="Place order">Send email</button></b></td>
			    <td><a href="{% url 'service:delete_invoice' invoice.id %}"><button class="btn btn-danger" type="submit" value="Place order">Delete</button></b></td>
			  </tr>
			{% else %}
			  <tr>
			    <td>{{ invoice.created|date:"D M d Y" }}</td>
			    <td><a href="{% url 'service:invoice_detail' invoice.id %}" class="button light">{{ invoice.id }}</td>
			    <td>{{ invoice.user.username }}</td>
			    <td>sent: <b>{{ invoice.is_paid }}</b></td>
			    <td><b>{{ invoice.get_total_cost }}</b></td>
			    <td><a href="{% url 'service:unselect_item' invoice.id %}"><button class="btn btn-info" type="submit" value="Place order">Selected</button></b></a></td>
			    <td><a href="#"><button class="btn btn-warning" type="submit" value="Place order">Send email</button></b></a></td>
			    <td><a href="{% url 'service:delete_invoice' invoice.id %}"><button class="btn btn-danger" type="submit" value="Place order">Delete</button></b></a></td>
			  </tr>
			{% endif%}
		  {% endfor %}
		</table>

		</br>

		{% include "service/pagination.html" with page=invoice_list %}

		</br></br>
	</div>
{% endblock %}

service/templates/service/dashboard/manager/manager_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}



{% endblock %}



{% block content %}

<div class="container mt-5">
	<div class="row">
		<div class="card" style="width: 38rem;">
		  <div class="card-header">
		   <h2><b>{{ user.manager.title }}</b> Profile</h2>
		  </div>
		  <ul class="list-group list-group-flush">
		    <li class="list-group-item">Username : <b>{{ user.username }}</b></li>
		    <li class="list-group-item">Title : <b>{{ user.manager.title }}</b></li>
		    <li class="list-group-item">First name : <b>{{ user.first_name }}</b></li>
		    <li class="list-group-item">Last name : <b>{{ user.last_name }}</b></li>
		    <li class="list-group-item">Email : <b>{{ user.email }}</b></li>
		    <li class="list-group-item">Company : <b>{{ user.manager.company_name }}</b></li>
			<li class="list-group-item"><b>Demo version: You cannot edit your profile :)</b></li>
		  </ul>
		</div>
	</div>
</div>
{% endblock %}

service/templates/service/dashboard/manager/other.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}



{% endblock %}



{% block content %}

{% endblock %}

service/templates/service/dashboard/manager/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}

Search results

{% endblock %}



{% block content %}

<div class="container mt-5">

      <a href="{% url 'service:invoice' %}">
        <button type="button" class="btn btn-info mt-1 mb-4">List of invoices</button>
      </a>



      <h1 class="title mt-5">Search results</h1>


      <div class="password-list mt-5">

      {% for result in results %}

        <a href='{% url "service:invoice_detail" result.id %}'>{{ result }}</br></br></br></a>

      {% empty %}

      	No result. Try something else.

      {% endfor%}



{% endblock %}