invoice/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

app_name = 'invoice'

urlpatterns = [
	path('', views.index, name='index'),
]

invoiceplus/urls.py
from django.contrib import admin
from django.urls import path, include
# Uploaded Media Files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('all_safe_xxx_safe_all/', admin.site.urls),
	path('invoice/', include('invoice.urls', namespace='invoice')),
	path('dashboard/', include('service.urls', namespace='service')),
	path('', include('user.urls', namespace='user')),

]


# Media files URL 
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin

from django.conf.urls import (
    handler404, 
    handler500
)

from django.urls import path, include
from . import views

handler404 = 'user.views.custom_404'
handler500 = 'user.views.custom_500'


app_name = 'user'
urlpatterns = [
	path('', views.index, name='index'),	
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('list-of-invoices/', views.list_invoices, name='list_invoices'),
	path('detail-invoice/', views.detail_invoice, name='detail_invoice'),
	path('profile/', views.customer_profile, name='customer_profile'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models


User = settings.AUTH_USER_MODEL


class User(AbstractUser):
	is_customer = models.BooleanField(default=True)

class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	phone_number = models.CharField(max_length=10)
	city = models.CharField(max_length=30)
	state = models.CharField(max_length=30)
	postal_code = models.CharField(max_length=30)
	active = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.user.username
	

	# def get_absolute_url(self):
	# 	return reverse('user:customer_detail', kwargs={'pk': self.pk })

class Manager(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
	title = models.CharField(max_length=50)
	company_name = models.CharField(max_length=30)
	active = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.user.username

user/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from .models import Customer, Manager


User = get_user_model()


class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')



class ManagerForm(forms.ModelForm):
	class Meta:
		model = Manager
		fields = ('title', 'company_name')


class UserLoginForm(forms.Form):
    """Validate Login form username and password."""
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect password')
            if not user.is_active:
                raise forms.ValidationError('This user is not active')
        return super(UserLoginForm, self).clean(*args, **kwargs)

user/views.py
from django.shortcuts import (
	render,
	redirect,
	get_object_or_404
)


from django.http import Http404

from django.contrib.auth.decorators import login_required

from django.contrib.auth import authenticate, get_user_model

from django.contrib.auth import login, logout 

from .forms import UserLoginForm



def index(request):
	return render(request, 'user/index.html')	

def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password) 

        if user.is_active:
            if user.is_superuser or user.is_staff:
                login(request, user)
                return redirect('service:invoice')
            else:
                login(request, user)
                return redirect('user:list_invoices')

    context = {'form': form}
    return render(request, 'user/registration/login.html', context)


def logout_view(request):
	logout(request)
	return redirect('user:login')

@login_required
def list_invoices(request):
    pass
    return render(request, 'user/customer/list_invoices.html', context)

@login_required
def detail_invoice(request):
    pass
    return render(request, 'user/customer/list_invoices.html', context)

@login_required
def customer_profile(request):
    pass
    return render(request, 'user/customer/customer_profile.html', context)


def custom_404(request):
    """Handle error 404."""
    return render(request, 'templates/404.html')

def custom_500(request):
    """Handle error 500."""
    return render(request, 'templates/500.html')

user/templates/customer_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Invoxx | Invoice App </title>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 90%;
      }

      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }

      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head> 

    <body>

      {% if user.is_authenticated %}

        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #17a2b8">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="{% url 'user:invoice' %}" style="color: #fff"><b>Invoxx</b></a>
            <ul class="navbar-nav ml-auto 0">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:invoice' %}" style="color: #fff">Invoices<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:profile' %}" style="color: #fff">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:logout' %}" style="color: #fff">Log out</a>
              </li>
            </ul>
          </div>
        </nav>

      {% endif %}

      {% block content %}
      {% endblock %}

    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

user/templates/user_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Invoxx | Invoice App </title>
  </head> 
    <body>

      {% block content %}

      {% endblock %}
      
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>